# This workflow executes PDK syntax validation, linting, and unit testing
# against any code changes submitted to this module for the purpose of ensuring
# that changes with validation errors don't get committed to the repo.
name: pdk-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  validation:
    name: PDK validation checks
    strategy:
      matrix:
        version: [6, 7]
    runs-on: ubuntu-latest
    container:
      image: puppet/pdk:latest
    env:
      PATH: /opt/puppetlabs/pdk/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PDK Validation
        run: |
          cd $GITHUB_WORKSPACE
          pdk validate --puppet-version=${{ matrix. version }}

  unit-testing:
    name: PDK unit testing
    strategy:
      matrix:
        version: [6, 7]
    runs-on: ubuntu-latest
    container:
      image: puppet/pdk:latest
    env:
      PATH: /opt/puppetlabs/pdk/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PDK Unit Testing
        run: |
          cd $GITHUB_WORKSPACE
          pdk test unit --puppet-version=${{ matrix.version }}
